# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "BMW"
license = "MIT"
licenselink = "https://github.com/regisin/bmw/blob/master/LICENSE"
description = ""
homepage = "https://www.paregis.me/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Paulo Alexandre Regis"
  homepage = "https://www.paregis.me/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
